pipeline {
  agent any

  stages{
    stage("Initial Clean Up"){
      steps {
        dir ("${WORKSPACE}"){
          deleteDir()
        }
      }
    }
  }
  
  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing App"'
        }
      }
    }

    stage('Package') {
      steps {
        script {
          sh 'echo "Packaging App"'
        }
      }
    }

    stage('Deploy') {
      steps {
        script {
          sh 'echo "Deploying to Dev"'
        }
      }
    }

    stage('Clean Up') {
      steps {
        cleanWs()
      }
    }
   }
}